---
apiVersion: v1
kind: Service
metadata:
  name: valheim
  labels:
    app: valheim
spec:
  selector:
    app: valheim
  ports:
  - name: udp-app1
    port: 2456
    targetPort: 2456
    protocol: UDP
  - name: udp-app2
    port: 2457
    targetPort: 2457
    protocol: UDP
  - name: udp-app3
    port: 2458
    targetPort: 2458
    protocol: UDP
  type: LoadBalancer
---
# Manually create a secret object in the cluster containing the world password
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: valheim-secrets
# data:
#   password: <base64 encoded password>
# immutable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: valheim-config
data:
  valheim_server_name: "Dedicated"
  valheim_world_name: "Carapachay"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valheim
spec:
  selector:
    matchLabels:
      app: valheim
  serviceName: "valheim"
  template:
    metadata:
      labels:
        app: valheim
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: valheim
        image: guilledipa/valheim:latest
        env:
          - name: VALHEIM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: valheim-secrets
                key: password
          - name: VALHEIM_SERVER_NAME
            valueFrom:
              configMapKeyRef:
                name: valheim-config
                key: valheim_server_name
          - name: VALHEIM_WORLD_NAME
            valueFrom:
              configMapKeyRef:
                name: valheim-config
                key: valheim_world_name
        resources:
          limits:
            cpu: "8"
            memory: "16Gi"
          requests:
            cpu: "4"
            memory: "8Gi"
        ports:
        - containerPort: 2456
          protocol: UDP
          name: udp-app1
        - containerPort: 2457
          protocol: UDP
          name: udp-app2
        - containerPort: 24578
          protocol: UDP
          name: udp-app3
        volumeMounts:
        - name: world-data
          mountPath: /home/steam/valheim-data
  volumeClaimTemplates:
  - metadata:
      name: world-data
    spec:
      accessModes: 
        - "ReadWriteOnce"
      storageClassName: ssd
      resources:
        requests:
          storage: 10Gi
